In [11]:
import numpy as np

def doolittle_lu_decomposition(A):
    """
    Performs LU decomposition on matrix A using Doolittle's method.
    Returns L (with 1's on diagonal) and U such that A = L * U.
    """
    n = len(A)
    # Initialize L as identity matrix and U as zero matrix
    L = np.eye(n)  # Identity matrix (1's on diagonal, 0's elsewhere)
    U = np.zeros((n, n))
    
    print("Starting Doolittle LU Decomposition")
    print("Initial L matrix:\n", L)
    print("Initial U matrix:\n", U)
    print("-" * 50)
    
    # Decomposition process
    for k in range(n):  # For each row/column
        print(f"Step {k+1}: Processing row/column {k}")
        
        # Calculate elements of the k-th row of U
        for j in range(k, n):
            print(f"  Calculating U[{k},{j}]")
            sum_val = 0.0
            # Summation: Σ (L[k][m] * U[m][j]) for m=0 to k-1
            for m in range(k):
                print(f"    Adding L[{k},{m}] * U[{m},{j}] = {L[k,m]} * {U[m,j]}")
                sum_val += L[k, m] * U[m, j]
            
            U[k, j] = A[k, j] - sum_val
            print(f"    U[{k},{j}] = A[{k},{j}] - sum = {A[k,j]} - {sum_val} = {U[k,j]}")
        
        # Calculate elements of the k-th column of L (for i > k)
        for i in range(k+1, n):
            print(f"  Calculating L[{i},{k}]")
            sum_val = 0.0
            # Summation: Σ (L[i][m] * U[m][k]) for m=0 to k-1
            for m in range(k):
                print(f"    Adding L[{i},{m}] * U[{m},{k}] = {L[i,m]} * {U[m,k]}")
                sum_val += L[i, m] * U[m, k]
            
            L[i, k] = (A[i, k] - sum_val) / U[k, k]
            print(f"    L[{i},{k}] = (A[{i},{k}] - sum) / U[{k},{k}] = ({A[i,k]} - {sum_val}) / {U[k,k]} = {L[i,k]}")
        
        print(f"After step {k+1}:")
        print("L =\n", L)
        print("U =\n", U)
        print("-" * 50)
    
    return L, U

# Test with our 2x2 example
#A = np.array([[2.0, 1.0],
#              [1.0, 3.0]])

# Test with our 3x3 example
A = np.array([
    [2, 1, -1],
    [-3, -1, 2],
    [-2, 1, 2]
])

print("Original matrix A:")
print(A)
print()

# Perform LU decomposition
L, U = doolittle_lu_decomposition(A)

print("Final Result:")
print("L matrix (lower triangular with 1's on diagonal):")
print(L)
print("U matrix (upper triangular):")
print(U)
print()

# Verify the decomposition
print("Verification: L * U should equal A")
print("L * U =")
print(np.dot(L, U))
print("Original A =")
print(A)


Original matrix A:
[[ 2  1 -1]
 [-3 -1  2]
 [-2  1  2]]

Starting Doolittle LU Decomposition
Initial L matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Initial U matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------------------------------------------------
Step 1: Processing row/column 0
  Calculating U[0,0]
    U[0,0] = A[0,0] - sum = 2 - 0.0 = 2.0
  Calculating U[0,1]
    U[0,1] = A[0,1] - sum = 1 - 0.0 = 1.0
  Calculating U[0,2]
    U[0,2] = A[0,2] - sum = -1 - 0.0 = -1.0
  Calculating L[1,0]
    L[1,0] = (A[1,0] - sum) / U[0,0] = (-3 - 0.0) / 2.0 = -1.5
  Calculating L[2,0]
    L[2,0] = (A[2,0] - sum) / U[0,0] = (-2 - 0.0) / 2.0 = -1.0
After step 1:
L =
 [[ 1.   0.   0. ]
 [-1.5  1.   0. ]
 [-1.   0.   1. ]]
U =
 [[ 2.  1. -1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
--------------------------------------------------
Step 2: Processing row/column 1
  Calculating U[1,1]
    Adding L[1,0] * U[0,1] = -1.5 * 1.0
    U[1,1] = A[1,1] - sum = -1 - -1.5 = 0.5
  Calculating U[1,2]
    Adding L[1,0] *