In [12]:
import numpy as np
from scipy.linalg import lu

# Define your matrix
A = np.array([
    [2.0, 1.0, -1.0],
    [-3.0, -1.0, 2.0],
    [-2.0, 1.0, 2.0]
])

print("Original matrix A:")
print(A)

# Perform LU decomposition with partial pivoting
# This is the professional, industry-standard method
P, L, U = lu(A)

print("\nResult from SciPy's lu() function (with Pivoting):")
print("P (Permutation matrix - records row swaps):")
print(P)
print("L (Lower triangular):")
print(L)
print("U (Upper triangular):")
print(U)

# Verify the decomposition: P * A = L * U
print("\nVerification: P * A should equal L * U")
print("P * A =")
print(P @ A) # Matrix multiplication
print("L * U =")
print(L @ U)


Original matrix A:
[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]

Result from SciPy's lu() function (with Pivoting):
P (Permutation matrix - records row swaps):
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L (Lower triangular):
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [-0.66666667  0.2         1.        ]]
U (Upper triangular):
[[-3.         -1.          2.        ]
 [ 0.          1.66666667  0.66666667]
 [ 0.          0.          0.2       ]]

Verification: P * A should equal L * U
P * A =
[[-2.  1.  2.]
 [ 2.  1. -1.]
 [-3. -1.  2.]]
L * U =
[[-3. -1.  2.]
 [-2.  1.  2.]
 [ 2.  1. -1.]]
